version: "3"
services:
  database:
    container_name: growbud_db
    image: postgres
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: growbud_dev

  growbud_server:
    container_name: growbud_server
    build:
      context: ./server
    command: bash -c "mix deps.get && mix ecto.setup && mix phx.server"
    depends_on:
      - database
    ports:
      - "4000:4000"
    volumes:
      - "./server/growbud:/app/"
    environment:
      - Mix.env=dev

  growbud_client:
    container_name: growbud_client
    build:
      context: ./client
    ports:
      - "8080:8080"
    volumes:
      - "./client/:/client"
    environment:
      - CHOKIDAR_USEPOLLING=true
