version: "3"
services:
  growbud_data_store:
    container_name: growbud_data_store
    build:
      context: ./server/data-store
    ports:
      - "9090:9090"
    volumes:
      - "./server/data-store/:/app"

  growbud_client:
    container_name: growbud_client
    build:
      context: ./client
    ports:
      - "8080:8080"
    volumes:
      - "./client/:/client"
    environment:
      - CHOKIDAR_USEPOLLING=true
