graph TD;
User-->Site;
User-->Harvest;
User-->Water;
User-->Entry;
User-->Content;
Harvest-->Crop;
Water-->Crop;
Administrator-->Content;
Site-->Dimension;
Site-->Layout;
Site-->Location;
Site-->Bed;
Site-->Container;
Site-->Calendar;
Container-->Substrate;
Container-->Layout;
Container-->Dimension;
Bed-->Substrate;
Bed-->Layout;
Bed-->Dimension;
Grow-->Technique;
Grow-->Style;
Seed-->Substrate;
Seed-->Germinate;
Crop-->Substrate;
Water-->Substrate;
Weather-->Forecast;
Season-->Weather;
Entry-->Journal;
Content-->Seed;
Content-->Crop;
Content-->Grow;
