graph TD;
Administrator-->Content;
Bed-->Substrate;
Bed-->Layout;
Bed-->Dimension;
Content-->Seed;
Content-->Crop;
Content-->Grow;
Container-->Substrate;
Container-->Layout;
Container-->Dimension;
Crop-->Substrate;
Entry-->Journal;
Grow-->Technique;
Grow-->Style;
Harvest-->Crop;
Site-->Dimension;
Site-->Layout;
Site-->Location;
Site-->Bed;
Site-->Container;
Site-->Calendar;
Season-->Site;
Seed-->Substrate;
Seed-->Germinate;
User-->Site;
User-->Harvest;
User-->Water;
User-->Entry;
User-->Content;
User-->WeatherForecast;
WeatherForecast-->Site;
Water-->Crop;
Water-->Substrate;
