openapi: "3.0.0"
info:
  title: Growbud API
  description: Growbud REST API documentation
  license:
    name: Apache 2.0
    url: https://github.com/OAI/OpenAPI-Specification/blob/master/https://www.apache.org/licenses/LICENSE-2.0.html
  version: 1.0.0

servers:
- url: https://localhost:5001
  description: Local Development server

paths:
  /auth/logout:
    post:
      tags:
       - auth
      description: Log out a user form Growbud.
      responses:
        '204':
          $ref: '#/components/responses/NoContent'

components:
  responses:
    NoContent:
      description: No Content
tags:
  - name: auth
    description: Authentication