openapi: "3.0.0"
info:
  title: Growbud API
  description: Growbud REST API documentation
  license:
    name: Apache 2.0
    url: https://github.com/OAI/OpenAPI-Specification/blob/master/https://www.apache.org/licenses/LICENSE-2.0.html
  version: 1.0.0

servers:
- url: https://localhost:5001
  description: Local Development server

paths:
  /auth/logout:
    post:
      parameters:
        - authorization:
          $ref: '#/components/parameters/AuthenticationToken'
      tags:
       - auth
      description: Log out a user form Growbud.
      responses:
        '204':
          $ref: '#/components/responses/NoContent'

components:
  responses:
    NoContent:
      description: No Content

  parameters:
    AuthenticationToken:
      name: Authentication token
      in: header
      description: JWT to be passed as a header.
      required: true
      schema:
        type: string

  securitySchemes:
    JWT:
      description: Authorization header.
      type: http
      scheme: bearer
      bearerFormat: JWT
tags:
  - name: auth
    description: Authentication