name: Firebase Deploy

on:
  push:
    branches:
      - master

    paths:
      - "client/**"

jobs:
  build:
    name: Build and Deploy master
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v2
      - name: Install Dependencies
        run: |
          cd client
          npm install
          npm run lint
      - name: Build
        run: |
          cd client
          npm run build
      - name: Deploy to Firebase
        uses: w9jds/firebase-action@v1.3.0
        with:
          args: deploy --only hosting:growbud-master
        env:
          GCP_SA_KEY: ${{ secrets.MASTER_GCP_SA_KEY }}
          PROJECT-PATH: ./client
