name: Firebase Deploy

on:
  push:
    branches:
      - master

    paths:
      - "client/**"

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v2
      - name: Install Dependencies
        run: |
          cd client
          npm install
          npm run lint
      - name: Build
        run: |
          cd client
          npm run build
      - name: Archive Production Artifact
        uses: actions/upload-artifact@v1
        with:
          name: client-${GITHUB_REF}
          path: client/dist
  deploy:
    name: Deploy
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v2
      - name: Download Artifact
        uses: actions/download-artifact@v1
        with:
          name: client-${GITHUB_REF}
      - name: Deploy to Firebase
        uses: w9jds/firebase-action@v1.3.0
        with:
          args: deploy --only hosting:growbud-master
        env:
          GCP_SA_KEY: ${{ secrets.MASTER_GCP_SA_KEY }}
          PROJECT-PATH: ./client
