name: Firebase Deploy

on:
  push:
    branches:
      - master

    paths:
      - 'client/**'

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@master
      - name: Install Dependencies
        run: |
          cd client
          npm install
      - name: Build
        run: |
          cd client
          npm run build
      - name: Archive Production Artifact
        uses: actions/upload-artifact@master
        with:
          name: webclient
          path: client/dist
  deploy:
    name: Deploy
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@master
      - name: Download Artifact
        uses: actions/download-artifact@master
        with:
          name: webclient
      - name: Deploy to Firebase
        uses: w9jds/firebase-action@develop
        with:
          args: deploy --only hosting:prod
        env:
          FIREBASE_TOKEN: ${{ secrets.FIREBASE_TOKEN }}
