name: Firebase Deploy

on:
  push:
    branches:
      - master

    paths:
      - "client/**"

jobs:
  build:
    name: Build and Deploy master
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v2
      - name: Install Dependencies
        run: |
          cd client
          npm install
          npm run lint
      - name: Deploy to Firebase
        uses: w9jds/firebase-action@v1.3.0
        with:
          args: deploy --only hosting
        env:
          FIREBASE_TOKEN: ${{ secrets.FIREBASE_TOKEN }}
