name: Data store deploy
on:
  push:
    branches:
      - master

    paths:
      - "server/data-store/**"

jobs:
  deploy:
    name: Deploy Data store
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@master
      - name: Install Server
        run: ./install-server.sh
      - name: Deploy to Firebase
        uses: w9jds/firebase-action@master
        with:
          args: deploy --only functions:dataStore
        env:
          FIREBASE_TOKEN: ${{ secrets.FIREBASE_TOKEN }}