name: Data store deploy
on:
  push:
    branches:
      - master

    paths:
      - "server/data-store/**"

jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v1
      - name: Install dependencies
        run: |
          cd server/data-store
          npm install
          npm run tsc-build
      - name: Push
        env:
          FIREBASEAPIKEY: ${{secrets.FIREBASEAPIKEY}}
          PROJECT_ID: ${{secrets.GCLOUD_PROJECT_ID}}
          APPLICATION_CREDENTIALS: ${{secrets.GOOGLE_APPLICATION_CREDENTIALS}}
        run: |
          cd server/data-store
          sed -i "s/fbapikey/$FIREBASEAPIKEY/g" app.yaml
      - uses: actions-hub/gcloud@master
        with:
          args: app deploy server/data-store/app.yaml
