name: Elixir CI

on:
  push:
    paths:
    - 'server/**'

jobs:
  test:
    runs-on: ubuntu-latest

    services:
      db:
        image: postgres:11
        ports: ['5432:5432']
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    steps:
      - uses: actions/checkout@v1.0.0
      - uses: actions/setup-elixir@v1.0.0
        with:
          otp-version: 22.x
          elixir-version: 1.9.x

      - name: Install Dependencies
        run: |
          cd server/growbud
          mix deps.get

      - name: Run Tests
        run: |
          cd server/growbud
          mix test
