name: Data store CI

on:
  push:
    branches:
      - master
    paths:
      - "server/notifications/**"

  pull_request:
    branches:
      - master
    paths:
      - "server/notifications/**"

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [10.x]

    steps:
      - uses: actions/checkout@v1
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - name: npm install and test
        run: |
          cd server/notifications
          npm install
          npm run build
        env:
          CI: true
